---
version: 0.2
phases:
  install:
    commands:
      - "python -m platform"
      - "cat /etc/docker.conf"
  build:
    commands:
      - "export version=2.7.15"
      - cd "/work"
      - ./centos_python.sh 2.7.15
#      - ./centos_python.sh 3.6.7
      - cd /u/python-2.7.15
      - zip -r -m /work/python-2.7.15.zip .
#      - cd /u/python-3.6.7
#      - zip -r -m /work/python-3.6.7.zip .
      - cd /work
      - ls -la
    # pre_build:
  # build:
  # post_build:
artifacts: {}
#  files:
#    - nginx-1.14.2.zip
#    - "maxmind-*.zip"
