---
version: 0.2
phases:
  install:
    commands:
      - "python -m platform"
      - "aws --version"
      - "cat /etc/docker.conf"
  build:
    commands:
      - "export version=2.7.15"
      - |
        cd "/work" \
          && ./centos_python.sh "${version}" \
          && cd /u/python-${version} \
          && zip -q -r -m ${CODEBUILD_SRC_DIR}/python-${version}.zip . \
          && aws s3 cp ${CODEBUILD_SRC_DIR}/python-${version}.zip s3://${Bucket}/
artifacts: {}
