#!/bin/bash
version=$(cat "VERSION")
name=$(cat "NAME")
image_url="https://index.docker.io/v1/repositories/${name}/tags/${version}"
version_exists=$(curl --silent -f -lSL ${image_url} >/dev/null)
if [[ ! version_exists ]] ; then
    docker build -f "${DOCKERFILE_PATH}" -t "${name}:${version}" -t "${name}:latest" .
else
    echo "nothing to build, version already exists."
fi
